<div class="fluid-container">
  <div class="row">
    <?php if (isset($data) && isset($data['firstName'])) : ?>
      <div class="col-md-3">
        <!-- DONUT CHART -->
        <a href="/auth/dashboard/leads/all/">
          <div class="box box-danger">
            <div class="box-header with-border">
              <h4 class="text-center">HUNT Leads Report</h4>
            </div>
            <div class="box-body">
              <canvas id="pieChart" height="150" width="150"></canvas>
            </div><!-- /.box-body -->
          </div><!-- /.box -->
        </a>
      </div>
    <?php else: ?>
      <p>This profile was not found</p>
    <?php endif; ?>
  </div><!--/row-->
</div><!--/.fluid-container-->

<script>
$(function() {
  var ctx = $("#pieChart").get(0).getContext("2d");
  var pieChart = new Chart( ctx );
  var pieData = [
    {
      value: 438,
      color:'#f56954',
      highlight:'#f56954'
    },
    {
      value:189,
      color:'#00a65a',
      highlight:'#00a65a'
    },
    {
      value:233,
      color:'#f39c12',
      highlight:'#f39c12'
    },
    {
      value: 51,
      color: '#3c8dbc',
      highlight: '#3c8dbc'
    },
    {
      value: 11,
      color:'#00c0ef',
      highlight:'#00c0ef'
    }
  ];
  var pieOptions = {
    //Boolean - Whether we should show a stroke on each segment
    segmentShowStroke: false,
    //String - The colour of each segment stroke
    segmentStrokeColor: "#fff",
    //Number - The width of each segment stroke
    segmentStrokeWidth: 2,
    //Number - The percentage of the chart that we cut out of the middle
    percentageInnerCutout: 50, // This is 0 for Pie charts
    //Number - Amount of animation steps
    animationSteps: 100,
    //String - Animation easing effect
    animationEasing: "easeOutBounce",
    //Boolean - Whether we animate the rotation of the Doughnut
    animateRotate: true,
    //Boolean - Whether we animate scaling the Doughnut from the centre
    animateScale: true,
    //Boolean - whether to make the chart responsive to window resizing
    responsive: true,
    // Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container
    maintainAspectRatio: false,
    //String - A legend template
    legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<segments.length; i++){%><li><span style=\"background-color:<%=segments[i].fillColor%>\"></span><%if(segments[i].label){%><%=segments[i].label%><%}%></li><%}%></ul>"
  };

  //Create pie or douhnut chart
  // You can switch between pie and douhnut using the method below.
  pieChart.Doughnut(pieData, pieOptions);

});
</script>
