<div class="fluid-container">
    <div class="row">
        <h1>Profile</h1>
        <?php if (isset($session_user) && isset($session_user['first_name'])) : ?>
            <h2>Hello, and welcome to <?= htmlspecialchars($session_user['first_name']); ?>'s dashboard!</h2>
        <?php else: ?>
            <p>This profile was not found</p>
        <?php endif; ?>
        <pre><?php var_dump($session_user); ?></pre>
    </div><!--/row-->
</div><!--/.fluid-container-->
